"use client";
import { useEffect, useState } from "react";
import SiteHeader from "../../components/site-header";
import ProjectSelector from "../../components/project-selector";
import { readProject, type ProjectRecord } from "../../lib/genlayer/data-source";
import { writeContract } from "../../lib/genlayer/contract";
import type { EthereumProvider } from "../../lib/genlayer/client";
declare global { interface Window { ethereum?: EthereumProvider } }
export default function Policy() { const [id, setId] = useState(0); const [project, setProject] = useState<ProjectRecord>(); const [style, setStyle] = useState(""); const [styleDigest, setStyleDigest] = useState(""); const [glossary, setGlossary] = useState(""); const [glossaryDigest, setGlossaryDigest] = useState(""); const [message, setMessage] = useState("Select a live project.");
 useEffect(() => { if (!id) return; void readProject(id).then((r) => { if (r.state === "ready") { setProject(r.value); setStyle(r.value.style_url); setStyleDigest(r.value.style_digest); setGlossary(r.value.glossary_url); setGlossaryDigest(r.value.glossary_digest); setMessage(""); } else setMessage(r.message); }); }, [id]);
 async function update() { const p = window.ethereum; const account = p ? (await p.request({ method: "eth_accounts" }) as string[])[0] : ""; if (!p || !account || !id) { setMessage("Connect an injected wallet and select a project."); return; } if (!/^https:\/\//.test(style) || !/^https:\/\//.test(glossary) || !/^[0-9a-f]{64}$/.test(styleDigest) || !/^[0-9a-f]{64}$/.test(glossaryDigest)) { setMessage("Use HTTPS URLs and lowercase SHA-256 digests."); return; } try { setMessage("Awaiting finalized policy update…"); await writeContract(account, p, "update_language_assets", [id, style, styleDigest, glossary, glossaryDigest]); const r = await readProject(id); if (r.state === "ready") { setProject(r.value); setMessage(`Policy v${r.value.policy_version} confirmed from chain.`); } } catch (e) { setMessage(e instanceof Error ? e.message : "Policy update failed."); } }
 return <main className="shell"><SiteHeader /><section className="workspace"><div className="eyebrow">PROJECT RULES · VERSIONED</div><h1>Glossary & style</h1><ProjectSelector value={id} onChange={setId} />{message && <p className="live-message">{message}</p>}{project && <div className="live-record"><p><strong>{project.name}</strong> · owner {project.owner}</p><p>Current policy version: {project.policy_version}</p><label>Style URL<input value={style} onChange={(e) => setStyle(e.target.value)} /></label><label>Style SHA-256<input value={styleDigest} onChange={(e) => setStyleDigest(e.target.value)} /></label><label>Glossary URL<input value={glossary} onChange={(e) => setGlossary(e.target.value)} /></label><label>Glossary SHA-256<input value={glossaryDigest} onChange={(e) => setGlossaryDigest(e.target.value)} /></label><button onClick={update}>Publish policy version</button></div>}</section></main>; }
