"use client";
import Link from "next/link";
import { useState } from "react";
import { listCases } from "../../lib/genlayer/data-source";
import SiteHeader from "../../components/site-header";
import ProjectSelector from "../../components/project-selector";
import { writeContract } from "../../lib/genlayer/contract";
import type { EthereumProvider } from "../../lib/genlayer/client";
import { discoverCaseId } from "../../lib/genlayer/validation";
declare global { interface Window { ethereum?: EthereumProvider } }
function placeholders(s: string) { return (s.match(/\{[^{}]+\}|%\w+/g) ?? []).sort().join("|"); }
export default function Queue() {
  const [project, setProject] = useState(0); const [createdCase, setCreatedCase] = useState(0); const [locale, setLocale] = useState("fr"); const [key, setKey] = useState(""); const [source, setSource] = useState(""); const [context, setContext] = useState(""); const [candidates, setCandidates] = useState(["", ""]); const [artifact, setArtifact] = useState(""); const [digest, setDigest] = useState(""); const [message, setMessage] = useState("Select a project to open a case.");
  async function submit() { const p = window.ethereum; const account = p ? (await p.request({ method: "eth_accounts" }) as string[])[0] : ""; const values = candidates.map((x) => x.trim()).filter(Boolean); if (!p || !account || !project) return setMessage("Connect an injected wallet and select a project."); if (!key || !source || !artifact.startsWith("https://") || !/^[0-9a-f]{64}$/.test(digest) || values.length < 2 || values.length > 5 || values.some((x) => placeholders(x) !== placeholders(source))) return setMessage("Provide valid fields, 2–5 candidates, HTTPS artifact and matching placeholders."); try { const beforeResult = await listCases(project, locale); const before = beforeResult.state === "ready" ? beforeResult.value : {}; setMessage("Submitting case and waiting for finality…"); const result = await writeContract(account, p, "open_case", [project, locale, key, source, context, JSON.stringify(values), artifact, digest]); const afterResult = await listCases(project, locale); const after = afterResult.state === "ready" ? afterResult.value : {}; const receiptId = Number((result.finalized as Record<string, unknown>).result ?? 0); const id = discoverCaseId(before, after, { project, locale, stringKey: key, source, artifact, digest }, receiptId); if (id > 0) { setCreatedCase(id); setMessage(result.verdict.indeterminate ? "Case finalized; execution evidence was incomplete. State reread from chain." : "Case created and confirmed from chain."); } else setMessage("Case finalized; no unambiguous matching case was found in the reread list."); } catch (e) { setMessage(e instanceof Error ? e.message : "Case submission failed."); } }
  return <main className="shell"><SiteHeader /><section className="workspace"><div className="eyebrow">STRING QUEUE · ESCALATION</div><h1>Open a disagreement case</h1><ProjectSelector value={project} onChange={setProject} /><p className="live-message">{message} {createdCase > 0 && <Link href={`/cases/${createdCase}`}>Inspect Case {createdCase}</Link>}</p><div className="live-record"><label>Locale<input value={locale} onChange={(e) => setLocale(e.target.value)} /></label><label>String key<input value={key} onChange={(e) => setKey(e.target.value)} /></label><label>Source text<textarea value={source} onChange={(e) => setSource(e.target.value)} /></label><label>Context<textarea value={context} onChange={(e) => setContext(e.target.value)} /></label>{candidates.map((value, i) => <label key={i}>Candidate {i + 1}<input value={value} onChange={(e) => setCandidates(candidates.map((x, j) => j === i ? e.target.value : x))} /></label>)}<button onClick={() => candidates.length < 5 && setCandidates([...candidates, ""])}>Add candidate</button><label>Artifact URL<input value={artifact} onChange={(e) => setArtifact(e.target.value)} /></label><label>Artifact SHA-256<input value={digest} onChange={(e) => setDigest(e.target.value)} /></label><button onClick={submit}>Submit case</button></div></section></main>;
}
