"use client";
import { useEffect, useState } from "react";
import { CONTRACT_ADDRESS } from "../lib/genlayer/config";
import { readProjects, type ProjectRecord } from "../lib/genlayer/data-source";
import { writeContract } from "../lib/genlayer/contract";
import type { EthereumProvider } from "../lib/genlayer/client";

declare global { interface Window { ethereum?: EthereumProvider } }
export default function LiveWorkspace() {
  const [projects, setProjects] = useState<Record<string, ProjectRecord>>({}); const [message, setMessage] = useState("Loading live contract state…"); const [account, setAccount] = useState<string | null>(null); const [name, setName] = useState(""); const [styleUrl, setStyleUrl] = useState(""); const [styleDigest, setStyleDigest] = useState(""); const [glossaryUrl, setGlossaryUrl] = useState(""); const [glossaryDigest, setGlossaryDigest] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { readProjects().then((result) => { if (result.state === "ready") { setProjects(result.value); setMessage(Object.keys(result.value).length ? "Select a project to begin." : "No projects exist on the configured contract."); } else setMessage(result.message); }); }, []);
  useEffect(() => { const p = window.ethereum; if (!p?.request) return; p.request({ method: "eth_accounts" }).then((a) => setAccount((a as string[])[0] ?? null)).catch(() => undefined); }, []);
  async function createProject() { const provider = window.ethereum; const digest = /^[0-9a-f]{64}$/; if (!provider || !account || !name.trim()) { setMessage("Connect an injected wallet and enter a project name."); return; } if (!styleUrl.startsWith("https://") || !glossaryUrl.startsWith("https://") || !digest.test(styleDigest) || !digest.test(glossaryDigest)) { setMessage("Provide HTTPS policy URLs and exact 64-character lowercase SHA-256 digests."); return; } setBusy(true); setMessage("Awaiting signature…"); try { await writeContract(account, provider, "create_project", [name.trim(), "en", styleUrl, styleDigest, glossaryUrl, glossaryDigest]); setMessage("Project created and verified from a fresh contract read."); const next = await readProjects(); if (next.state === "ready") setProjects(next.value); } catch (error) { setMessage(error instanceof Error ? error.message : "Project creation failed."); } finally { setBusy(false); } }
  return <div className="live-workspace"><div className="pane-head"><span>Authoritative projects</span><span>{CONTRACT_ADDRESS ? "LIVE" : "UNAVAILABLE"}</span></div><p className="live-message">{message}</p>{Object.entries(projects).map(([id, project]) => <div className="project-row" key={id}><strong>{project.name}</strong><span>Project {id} · policy v{project.policy_version} · {project.case_count} cases</span></div>)}<div className="create-line"><input aria-label="Project name" value={name} onChange={(event) => setName(event.target.value)} placeholder="New project name" /><input aria-label="Style URL" value={styleUrl} onChange={(event) => setStyleUrl(event.target.value)} placeholder="https://style URL" /><input aria-label="Style SHA-256" value={styleDigest} onChange={(event) => setStyleDigest(event.target.value)} placeholder="style SHA-256" /><input aria-label="Glossary URL" value={glossaryUrl} onChange={(event) => setGlossaryUrl(event.target.value)} placeholder="https://glossary URL" /><input aria-label="Glossary SHA-256" value={glossaryDigest} onChange={(event) => setGlossaryDigest(event.target.value)} placeholder="glossary SHA-256" /><button disabled={busy} onClick={createProject}>{busy ? "Working…" : "Create project"}</button></div></div>;
}
