"use client";
/* Reads synchronize UI state with the external contract after async completion. */
/* eslint-disable react-hooks/set-state-in-effect */
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { listCases, listReleases, parseJson, previewMemory, readCase, readProject, readRelease, type CaseRecord, type ProjectRecord, type ReleaseRecord } from "../lib/genlayer/data-source";
import { writeContract } from "../lib/genlayer/contract";
import type { EthereumProvider } from "../lib/genlayer/client";
declare global { interface Window { ethereum?: EthereumProvider } }
function State({ message }: { message: string }) { return <div className="empty-state"><strong>{message}</strong><p>Only verified contract state is displayed.</p></div>; }
export function ProjectPolicy({ id }: { id: number }) { const [value, setValue] = useState<ProjectRecord>(); const [message, setMessage] = useState("Loading project policy…"); useEffect(() => { void readProject(id).then((r) => r.state === "ready" ? (setValue(r.value), setMessage("")) : setMessage(r.message)); }, [id]); if (!value) return <State message={message} />; return <div className="live-record"><strong>{value.name}</strong><p>Owner {value.owner} · source {value.source_locale} · policy v{value.policy_version} · {value.case_count} cases</p><p>Style: {value.style_url} · {value.style_digest}</p><p>Glossary: {value.glossary_url} · {value.glossary_digest}</p></div>; }
export function CaseRecordView({ id }: { id: number }) { const [record, setRecord] = useState<CaseRecord>(); const [memory, setMemory] = useState<Array<Record<string, unknown>>>([]); const [message, setMessage] = useState("Loading case…"); const [busy, setBusy] = useState(false); const [replacement, setReplacement] = useState(""); const refresh = useCallback(async () => { const [c, m] = await Promise.all([readCase(id), previewMemory(id)]); if (c.state === "ready") { setRecord(c.value); setMessage(""); } else setMessage(c.message); if (m.state === "ready") setMemory(m.value); }, [id]); useEffect(() => { void refresh(); }, [refresh]); async function action(name: "resolve_case" | "supersede_case", args: unknown[]) { const p = window.ethereum; const account = p ? (await p.request({ method: "eth_accounts" }) as string[])[0] : ""; if (!p || !account) return setMessage("Connect an injected wallet to write."); try { setBusy(true); setMessage("Awaiting finalized GenVM execution…"); await writeContract(account, p, name, args); await refresh(); setMessage("Authoritative state refreshed after finality."); } catch (e) { setMessage(e instanceof Error ? e.message : "Transaction failed."); } finally { setBusy(false); } } if (!record) return <State message={message} />; const candidates = parseJson<string[]>(record.candidates_json, []); return <div className="live-record"><p><strong>{record.string_key}</strong> · {record.locale} · {record.status}</p><p>Project {record.project_id} · policy v{record.policy_version}</p><p>Source: {record.source_text}</p><p>Context: {record.context_text}</p><p>Candidates: {candidates.map((c, i) => <span key={i}>[{i}] {c} </span>)}</p><p>Artifact: {record.artifact_ref} · {record.artifact_digest}</p><p>Policy snapshot: {record.style_digest} · {record.glossary_digest}</p><p>Approved index: {record.approved_index} · rationale: {record.rationale || "—"}</p><p>Memory IDs: {record.memory_ids_json} · related valid memory: {memory.length}</p>{record.superseded_by > 0 && <p>Superseded by <Link href={`/cases/${record.superseded_by}`}>{record.superseded_by}</Link></p>}{record.status === "ESCALATED" && <button disabled={busy} onClick={() => action("resolve_case", [id])}>Resolve case</button>}{record.status === "APPROVED" && <div><input aria-label="Replacement case ID" value={replacement} onChange={(e) => setReplacement(e.target.value)} placeholder="Approved replacement case ID" /><button disabled={busy || !replacement} onClick={() => action("supersede_case", [id, Number(replacement)])}>Supersede with case</button></div>}<p>{message}</p></div>; }
export function ReleaseRecordView({ id }: { id: number }) { const [record, setRecord] = useState<ReleaseRecord>(); const [message, setMessage] = useState("Loading release receipt…"); useEffect(() => { void readRelease(id).then((r) => r.state === "ready" ? (setRecord(r.value), setMessage("")) : setMessage(r.message)); }, [id]); if (!record) return <State message={message} />; return <div className="live-record"><p><strong>Release {id}</strong> · project {record.project_id} · {record.locale} · policy v{record.policy_version}</p><p>Manifest: {record.manifest_url} · {record.manifest_digest}</p><p>Sealed at: {record.sealed_at}</p><p>Commitment digest: {record.commitment_digest}</p><pre>{record.commitment_json}</pre><p>Required cases: {record.required_case_ids_json}</p></div>; }
export function CaseList({ projectId, locale }: { projectId: number; locale: string }) { const [items, setItems] = useState<Record<string, CaseRecord>>({}); const [message, setMessage] = useState("Loading cases…"); useEffect(() => { void listCases(projectId, locale).then((r) => r.state === "ready" ? (setItems(r.value), setMessage("")) : setMessage(r.message)); }, [projectId, locale]); if (message) return <State message={message} />; return <div className="live-record">{Object.entries(items).map(([id, item]) => <p key={id}><Link href={`/cases/${id}`}><strong>Case {id}</strong></Link> · {item.string_key} · {item.status}</p>)}</div>; }
export function ReleaseList({ projectId, locale }: { projectId: number; locale: string }) { const [items, setItems] = useState<Record<string, ReleaseRecord>>({}); const [message, setMessage] = useState("Loading releases…"); useEffect(() => { void listReleases(projectId, locale).then((r) => r.state === "ready" ? (setItems(r.value), setMessage("")) : setMessage(r.message)); }, [projectId, locale]); if (message) return <State message={message} />; return <div className="live-record">{Object.entries(items).map(([id, item]) => <p key={id}><Link href={`/releases/${id}`}><strong>Release {id}</strong></Link> · policy v{item.policy_version} · {item.commitment_digest}</p>)}</div>; }
