"use client";
/* The initial read is an external contract synchronization, not derived state. */
/* eslint-disable react-hooks/set-state-in-effect */
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { CONTRACT_ADDRESS } from "../lib/genlayer/config";
import { readProjects, type ProjectRecord } from "../lib/genlayer/data-source";
import { writeContract } from "../lib/genlayer/contract";
import type { EthereumProvider } from "../lib/genlayer/client";
import { useSelectedProject } from "./project-selector";
declare global { interface Window { ethereum?: EthereumProvider } }
export default function LiveWorkspace() {
  const [projects, setProjects] = useState<Record<string, ProjectRecord>>({}); const [message, setMessage] = useState("Loading live contract state…"); const [account, setAccount] = useState<string | null>(null); const [name, setName] = useState(""); const [styleUrl, setStyleUrl] = useState(""); const [styleDigest, setStyleDigest] = useState(""); const [glossaryUrl, setGlossaryUrl] = useState(""); const [glossaryDigest, setGlossaryDigest] = useState(""); const [busy, setBusy] = useState(false); const { projectId, select } = useSelectedProject();
  const refresh = useCallback(async () => { const result = await readProjects(); if (result.state === "ready") { setProjects(result.value); setMessage(Object.keys(result.value).length ? "Select a project to begin." : "No projects exist on the configured contract."); } else setMessage(result.message); }, []);
  useEffect(() => { void refresh(); const p = window.ethereum; if (p?.request) void p.request({ method: "eth_accounts" }).then((a) => setAccount((a as string[])[0] ?? null)); }, [refresh]);
  async function createProject() { const provider = window.ethereum; if (!provider || !account || !name.trim()) { setMessage("Connect an injected wallet and enter a project name."); return; } const digest = /^[0-9a-f]{64}$/; if (!styleUrl.startsWith("https://") || !glossaryUrl.startsWith("https://") || !digest.test(styleDigest) || !digest.test(glossaryDigest)) { setMessage("Provide HTTPS policy URLs and exact 64-character lowercase SHA-256 digests."); return; } setBusy(true); setMessage("Awaiting signature and finalized GenVM execution…"); try { await writeContract(account, provider, "create_project", [name.trim(), "en", styleUrl, styleDigest, glossaryUrl, glossaryDigest]); await refresh(); setName(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Project creation failed."); } finally { setBusy(false); } }
  return <div className="live-workspace"><div className="pane-head"><span>Authoritative projects</span><span>{CONTRACT_ADDRESS ? "LIVE" : "UNAVAILABLE"}</span></div><p className="live-message">{message}</p>{Object.entries(projects).map(([id, project]) => <button className="project-row" key={id} onClick={() => select(Number(id))}><strong>{project.name}</strong><span>Project {id} · policy v{project.policy_version} · {project.case_count} cases</span></button>)}{projectId > 0 && <p className="live-message">Selected project {projectId}. <Link href={`/policy?project=${projectId}`}>Policy</Link> · <Link href={`/queue?project=${projectId}`}>Open case</Link> · <Link href={`/cases?project=${projectId}`}>Cases</Link> · <Link href={`/releases?project=${projectId}`}>Releases</Link></p>}<div className="create-line"><input aria-label="Project name" value={name} onChange={(e) => setName(e.target.value)} placeholder="New project name" /><input aria-label="Style URL" value={styleUrl} onChange={(e) => setStyleUrl(e.target.value)} placeholder="https://style URL" /><input aria-label="Style SHA-256" value={styleDigest} onChange={(e) => setStyleDigest(e.target.value)} placeholder="style SHA-256" /><input aria-label="Glossary URL" value={glossaryUrl} onChange={(e) => setGlossaryUrl(e.target.value)} placeholder="https://glossary URL" /><input aria-label="Glossary SHA-256" value={glossaryDigest} onChange={(e) => setGlossaryDigest(e.target.value)} placeholder="glossary SHA-256" /><button disabled={busy} onClick={createProject}>{busy ? "Working…" : "Create project"}</button></div></div>;
}
