"use client";
import { useEffect, useState } from "react";
import SiteHeader from "../../components/site-header";
import ProjectSelector from "../../components/project-selector";
import { listCases, type CaseRecord } from "../../lib/genlayer/data-source";
import { writeContract } from "../../lib/genlayer/contract";
import { ReleaseList } from "../../components/live-records";
import type { EthereumProvider } from "../../lib/genlayer/client";
declare global { interface Window { ethereum?: EthereumProvider } }
export default function Releases() { const [project, setProject] = useState(0); const [locale, setLocale] = useState("fr"); const [cases, setCases] = useState<Record<string, CaseRecord>>({}); const [selected, setSelected] = useState<string[]>([]); const [manifest, setManifest] = useState(""); const [digest, setDigest] = useState(""); const [message, setMessage] = useState("Select a project to build a release."); useEffect(() => { if (project) void listCases(project, locale).then((r) => r.state === "ready" ? (setCases(r.value), setMessage("")) : setMessage(r.message)); }, [project, locale]); async function seal() { const p = window.ethereum; const account = p ? (await p.request({ method: "eth_accounts" }) as string[])[0] : ""; if (!p || !account || !project || !manifest.startsWith("https://") || !/^[0-9a-f]{64}$/.test(digest) || !selected.length || new Set(selected).size !== selected.length) return setMessage("Select approved cases and provide an HTTPS manifest with a lowercase SHA-256 digest."); if (selected.some((id) => cases[id]?.status !== "APPROVED")) return setMessage("Only approved cases can be sealed."); try { setMessage("Awaiting finalized release seal…"); await writeContract(account, p, "seal_release", [project, locale, manifest, digest, JSON.stringify(selected.map(Number))]); setMessage("Release sealed; refresh the release list to inspect the receipt."); } catch (e) { setMessage(e instanceof Error ? e.message : "Release sealing failed."); } } return <main className="shell"><SiteHeader /><section className="workspace"><div className="eyebrow">LOCALE RELEASES · IMMUTABLE RECEIPTS</div><h1>Release checklist</h1><ProjectSelector value={project} onChange={setProject} /><label>Locale<input value={locale} onChange={(e) => setLocale(e.target.value)} /></label><p className="live-message">{message}</p><div className="live-record">{Object.entries(cases).map(([id, c]) => <label key={id}><input type="checkbox" disabled={c.status !== "APPROVED"} checked={selected.includes(id)} onChange={() => setSelected(selected.includes(id) ? selected.filter((x) => x !== id) : [...selected, id])} /> Case {id} · {c.string_key} · {c.status}</label>)}<label>Manifest URL<input value={manifest} onChange={(e) => setManifest(e.target.value)} /></label><label>Manifest SHA-256<input value={digest} onChange={(e) => setDigest(e.target.value)} /></label><button onClick={seal}>Seal release</button></div>{project > 0 && <ReleaseList projectId={project} locale={locale} />}</section></main>; }
